# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f281d695341c760ff90142c1f47293db78642589f6adc4c326c6a941ce22dd2c2eca64dc87e2a49cc961fd37b5af1d66b2757e90041db448122c09b6361381c9

test:
  secret_key_base: 2e21f972a818dc16359d249130d1e8fbe61d20331456b83c219ef455a9aa555dfa0f3426df9ad41a9cb802e074ed7cbefce5630d0eadd927243e8878eb6c06d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
